FROM node:22.19.0 AS build

RUN apt-get update
RUN apt-get install -y git

RUN mkdir /opt/app
WORKDIR /opt/app
RUN git clone https://github.com/lgonzalezmislata/tienda-front.git
WORKDIR /opt/app/tienda-front
RUN npm install
RUN npm run build --prod

# Etapa 2: servidor web
FROM nginx:1.28.0-alpine3.21
COPY --from=build /opt/app/tienda-front/dist/tienda-front/browser/ /usr/share/nginx/html

