FROM maven:3.9.11-eclipse-temurin-21-noble

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y git

RUN mkdir /opt/app
WORKDIR /opt/app
RUN git clone https://github.com/lgonzalezmislata/tienda-back.git
WORKDIR /opt/app/tienda-back
RUN mvn clean install
CMD ["java","-jar", "target/tienda-back-0.0.1-SNAPSHOT.jar"]




